wkn1    #configuration modified to use separate physical interfaces for node and infra networks
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocp4isw
rendezvousIP: 172.31.32. 
AdditionalNTPSources:
  - time.cisco.com
hosts:
  - hostname: cp1
    role: master
    interfaces:
    - name: ens160
      macAddress: 00:50:56:97:16:db
    - name: ens161
      macAddress: 00:50:56:97:16:dc
    networkConfig:
      interfaces:
        - name: ens160
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens161
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: node
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens160
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.3
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
        - name: infra
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens161
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: node
          - destination: 224.0.0.0/4
            next-hop-interface: infra

  - hostname: cp2
    role: master
    interfaces:
    - name: ens160
      macAddress: 00:50:56:97:16:dd
    - name: ens161
      macAddress: 00:50:56:97:16:de
    networkConfig:
      interfaces:
        - name: ens160
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens161
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: node
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens160
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.4
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
        - name: infra
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens161
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: node
          - destination: 224.0.0.0/4
            next-hop-interface: infra

  - hostname: cp3
    role: master
    interfaces:
    - name: ens160
      macAddress: 00:50:56:97:16:df
    - name: ens161
      macAddress: 00:50:56:97:16:e0
    networkConfig:
      interfaces:
        - name: ens160
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens161
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: node
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens160
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.5
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
        - name: infra
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens161
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: node
          - destination: 224.0.0.0/4
            next-hop-interface: infra

  - hostname: wkn1
    role: worker
    interfaces:
    - name: ens160
      macAddress: ec:b1:d7:b1:e4:f0
    - name: ens161
      macAddress: ec:b1:d7:b1:e4:f4
    networkConfig:
      interfaces:
        - name: ens160
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens161
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: node
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens160
          ipv4:
            enabled: true
            address:
              - ip: 172.31.32.108
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
        - name: infra
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens161
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 172.25.15.7
            - 172.25.15.68
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: node
          - destination: 224.0.0.0/4
            next-hop-interface: infra

  - hostname: wkn2
    role: worker
    interfaces:
    - name: ens160
      macAddress: 58:20:b1:e1:12:78
    - name: ens161
      macAddress: 58:20:b1:e1:12:76
    networkConfig:
      interfaces:
        - name: ens160
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens161
          mtu: 9000
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: node
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens160
          ipv4:
            enabled: true
            address:
              - ip: 172.31.32.109
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
        - name: infra
          type: physical
          mtu: 9000
          state: up
          physical:
            base-iface: ens161
          ipv4:
            enabled: true
            dhcp: true
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 172.25.15.7
            - 172.25.15.68
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: node
          - destination: 224.0.0.0/4
            next-hop-interface: infra
                     